### PR TITLE
assert_ok: Remove `Debug` requirement for `Ok()` content

### LINKED ISSUE #2: `assert_ok!` requires `Ok()` content to have `Debug` implementation
The way the `assert_ok!()` macro is currently implemented it prints the debug version of the `Err()` content if the result is an error, but it never prints the `Ok()` content. It still seems to require that the `Ok()` content has a `Debug` implementation though, which seems unnecessarily constraining in some cases.

### PR DESCRIPTION
**Pull request by Turbo87**
This resolves #2 :)

If there is interest, I can create a similar PR for `assert_err!()` too.

### CODE REVIEW

**Comment by svartalf** [comment]
Looks great!

Any ideas what is happening with Rust 1.15.0 build? Not sure what might cause it here

**Comment by Turbo87** [comment]
> Any ideas what is happening with Rust 1.15.0 build? Not sure what might cause it here

nope, I'm currently trying to figure it out, but I'm starting to get out of ideas 😅

**Comment by Turbo87** [comment]
Still haven't found an explanation for why this is breaking on Rust v1.15. https://github.com/rust-lang/rust/issues/34537 is not that helpful either in this case since it does not talk about `forbid` at all.

I've found a way to work around it for now, which is disabling the `tests` module when running with Rust v1.15. Certainly not a particularly great solution, but I'm out of ideas. 😞

**Comment by Turbo87** [comment]
I've added similar tests for `assert_err!()` and `assert_some!()` now too

**Comment by svartalf** [comment]
Awesome investigation! It does looks like some kind of Rust regression (?), skipping these tests for Rust 1.15 is okay for me.

Is there any other changes you want to add also?

**Comment by Turbo87** [comment]
> Is there any other changes you want to add also?

my goal was to allow us to use `claim` in the crates.io codebase to replace our custom `t!()` macro, and I think these changes should be sufficient for now to allow that. if anything else comes up I might open more PRs :)

**Comment by svartalf** [comment]
Great to hear! Published your changes in the [`claim = "0.4.0"`](https://crates.io/crates/claim/0.4.0)

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io/pull/2962 😉

**Pull request merged**
